const getMockSummary = (title, content) => {
  return `### 📝 Study Summary: ${title || "Untitled Note"}

This note focuses on the core concepts of **${title || "this study topic"}**. Here is a structured summary of the main ideas:

#### Key Takeaways
1. **Core Concept**: The material outlines the fundamentals and structural foundation of this topic.
2. **Key Definitions**: Important terminology and definitions that are vital for exam preparation.
3. **Practical Application**: How these concepts apply in real-world scenarios and software engineering.

#### Detailed Breakdown
- **Important Points**:
  - The content suggests a systematic methodology for studying and applying these concepts.
  - Pay close attention to how various components interact.
- **Action Items**:
  - [ ] Review the syntax and design rules associated with this topic.
  - [ ] Implement a mini-project or solve practice questions.
  - [ ] Discuss key problem-solving techniques with peers.

---
*Generated by EduVerse AI Assistant*`;
};

const getMockExplanation = (topic) => {
  return `### 💡 Topic Explanation: ${topic}

Here is a simplified, comprehensive explanation of **${topic}** designed to build deep conceptual understanding:

#### 1. What is it?
At its core, **${topic}** is a concept used to solve specific sets of problems efficiently. Think of it like a structured toolkit: instead of reinventing the wheel, we use these established patterns to save time and optimize performance.

#### 2. Key Concepts & Principles
- **Efficiency**: It aims to reduce time complexity or resource consumption.
- **Modularity**: Organizes complex operations into smaller, manageable, and understandable parts.
- **Reliability**: Relies on proven mathematical or logical structures.

#### 3. Real-World Analogy
Imagine organizing books in a library. Instead of throwing them in a pile, you sort them alphabetically or by subject. **${topic}** acts as the library's sorting system, making it easy to retrieve any book instantly.

#### 4. Common Pitfalls
* Confusing theoretical execution with practical constraints.
* Over-engineering simple use cases.

---
*Generated by EduVerse AI Assistant*`;
};

const getMockQuiz = (topic) => {
  return `### ✍️ Generated Quiz: ${topic}
Test your knowledge on this subject. Answer the questions and review the key.

#### Question 1
What is the primary objective of studying **${topic}**?
- [A] To increase code complexity
- [B] To optimize efficiency, readability, and performance (Correct)
- [C] To store files on local storage only
- [D] None of the above

#### Question 2
Which of the following is a common practice when applying **${topic}**?
- [A] Ignoring edge cases and errors
- [B] Writing monolithic scripts
- [C] Decomposing complex problems into modular functions (Correct)
- [D] Hardcoding variables

#### Question 3
True or False: **${topic}** is only relevant to advanced software architectures.
- [A] True
- [B] False (Correct - it applies to all levels of system design)

---
*Generated by EduVerse AI Assistant*`;
};

const getMockRecommendations = (notesCount, goalsCount, focusHours) => {
  return `### 🚀 Personal Study Recommendations

Based on your current activity (${notesCount} notes, ${goalsCount} goals, ${focusHours} hrs focused), here is your personalized study plan:

#### 📈 Focus Areas
1. **Focus consistency**: You have logged **${focusHours} hours** of study time. Try setting a goal for a daily 25-minute Pomodoro session to build muscle memory.
2. **Notes Integration**: With **${notesCount} notes** saved, consider using the *AI Quiz* generator on your recent notes to self-test before exams.
3. **Goal Alignment**: You have **${goalsCount} active goals**. Group them into "High Priority" first to avoid multitasking fatigue.

#### 💡 Daily Tips
* **Active Recall**: Don't just re-read notes. Close the tab and write down everything you remember, then check your accuracy.
* **Spaced Repetition**: Re-visit new notes after 1 day, 3 days, and then 7 days.
* **Lofi Focus**: Use the Focus Room's ambient background sounds to minimize external noise.

---
*Generated by EduVerse AI Assistant*`;
};

const summarizeNote = async (title, content) => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey || apiKey === "mock_key") {
    return getMockSummary(title, content);
  }

  try {
    const prompt = `Summarize the following study note. Note Title: ${title}. Content: ${content}. Provide key concepts, bullet points, definitions, and action items in clean Markdown.`;
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
        }),
      }
    );
    const data = await response.json();
    return data.candidates[0].content.parts[0].text;
  } catch (error) {
    console.error("AI API Error, falling back to mock:", error.message);
    return getMockSummary(title, content);
  }
};

const explainTopic = async (topic) => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey || apiKey === "mock_key") {
    return getMockExplanation(topic);
  }

  try {
    const prompt = `Explain the academic topic: "${topic}" in detail for a college student. Include definitions, key concepts, a real-world analogy, and common mistakes. Format in clean Markdown.`;
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
        }),
      }
    );
    const data = await response.json();
    return data.candidates[0].content.parts[0].text;
  } catch (error) {
    console.error("AI API Error, falling back to mock:", error.message);
    return getMockExplanation(topic);
  }
};

const generateQuiz = async (topic) => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey || apiKey === "mock_key") {
    return getMockQuiz(topic);
  }

  try {
    const prompt = `Create a 3-question multiple choice quiz about "${topic}" for test preparation. For each question, indicate the correct answer and a brief explanation. Format in clean Markdown.`;
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
        }),
      }
    );
    const data = await response.json();
    return data.candidates[0].content.parts[0].text;
  } catch (error) {
    console.error("AI API Error, falling back to mock:", error.message);
    return getMockQuiz(topic);
  }
};

const getRecommendations = async (notesCount, goalsCount, focusHours) => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey || apiKey === "mock_key") {
    return getMockRecommendations(notesCount, goalsCount, focusHours);
  }

  try {
    const prompt = `Provide 3 personalized study recommendations and productivity hacks for a student who has saved ${notesCount} notes, set ${goalsCount} study goals, and finished ${focusHours} hours of focused work on their dashboard. Format in clean Markdown.`;
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
        }),
      }
    );
    const data = await response.json();
    return data.candidates[0].content.parts[0].text;
  } catch (error) {
    console.error("AI API Error, falling back to mock:", error.message);
    return getMockRecommendations(notesCount, goalsCount, focusHours);
  }
};

module.exports = {
  summarizeNote,
  explainTopic,
  generateQuiz,
  getRecommendations,
};
